### ISSUE TITLE
Add a contact / feedback form

### ISSUE THREAD

**Issue by trex** [trex/hawthorn-client#5]
Add a form that people can use to leave feedback or get involved with the project.

Should this form send an email, ping in discord, other ideas?

**Comment by moonquay** [comment]
Good idea, I think that would be a good link throughout the website as well as at the end of the /about page.
A basic email one sounds good, but I interested in learning of the pros/cons of using other input mediums.

**Comment by trex** [comment]
We could also do push notifications, post to a Slack channel, put an entry in the database...

Email might be best initially, since we don't have a coordinated communication system.  This way we can adjust the email address that this form sends to as time goes on to send to whatever individual or group it makes the most sense to receive this communication.

**Comment by trex** [comment]
I added a contact form that is an embedded google form.  The form has optional "Name", "Email", and "Subscribe to Newsletter" fields, and a required "Feedback" field.  It will send me an email notification when anyone submits the form.
